---
- hosts: localhost
  pre_tasks:
    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: false

      # TODO
      # ew. ustawienie liczby wyświetlanych katalogów w promptcie agnostera
  tasks:
    - include: tasks/shell.yml
      tags: shell
    - include: tasks/vim.yml
      tags: vim
    - include: tasks/desktop.yml
      tags: desktop
